### ISSUE TITLE
Armour rendering and layer rendering is bugged

### ISSUE THREAD

**Issue by GreenShaman** [fewizz/Crawl#1]
![Screenshot 2019-04-04 19 50 14](https://user-images.githubusercontent.com/7545132/55580729-2055cd80-5713-11e9-850c-b53ee34515ee.png)

**Comment by fewizz** [comment]
Yay, first issue :fire:

**Comment by fewizz** [comment]
https://minecraft.curseforge.com/projects/crawl/files/2695631
