### ISSUE TITLE
Compatibility Request: Bedrockify

### ISSUE THREAD

**Issue by beforetimeitself** [fewizz/Crawl#12]
First of all, I love this mod. It's adorable and very handy. Second, I'd love to see this compatible with [bedrockify](https://www.curseforge.com/minecraft/mc-mods/bedrockify). The issue is that Bedrockify's "paper doll" feature isn't working with the crawl animation. I asked the bedrock developer first but it appears as though the problem is coming from your end. Seeing as how I can only see the crawl animation through 3rd person I'd really like to see it in 1st person even if it's in the corner. Thank you all for your work.

**Comment by fewizz** [comment]
https://github.com/juancarloscp52/BedrockIfy/pull/34
