### ISSUE TITLE
transition animation looks wierd

### ISSUE THREAD

**Issue by RyanCR03** [fewizz/Crawl#13]
when the crawling transition plays the player's head bobs and if the player is wearing a cape it goes through the body 
[here is a video showing the different angles](https://youtu.be/PLKX4I9kSFA)

**Comment by fewizz** [comment]
![crawl](https://user-images.githubusercontent.com/8060034/100716284-8c497700-33c9-11eb-9ae0-4571b5d83631.gif)
What about this? It's simpler

**Comment by RyanCR03** [comment]
that looks great! I feel like it would match up with the swimming animation and it looks a lot minecraftier.
