### ISSUE TITLE
[Suggestion] More animations

### ISSUE THREAD

**Issue by RyanCR03** [fewizz/Crawl#15]
it would be nice if there were different custom animations than just crawling
[here is an image of what I was thinking](https://imgur.com/MZZAkIo)

**Comment by fewizz** [comment]
Then i should change mod name...

**Comment by RyanCR03** [comment]
you could add the diving animation to this mod without changing the name and another option to add the animations would be to create a new mod

**Comment by fewizz** [comment]
I will do that, but not this year

**Comment by fewizz** [comment]
Out of mod's scope.
