### ISSUE TITLE
Infinitely load on mojang loading screen on 1.17

### ISSUE THREAD

**Issue by Zano1999** [fewizz/Crawl#24]
It infinitely load the mojang logo screen with your latest version of the mod in 1.17, below i post the latest log file (it's too long for pastebin).
[log.txt](https://github.com/fewizz/crawl/files/6910082/log.txt)
If the download don't work here a dropbow link to the file: https://www.dropbox.com/s/68y578lmgiyp9bd/log.txt?dl=0

**Comment by WaldoTheRanger** [comment]
I had this issue, but it was because of a conflict with "Emotecraft"
If you're also using emotecraft, try disabling that
Otherwise i'd suggest trying to find which other mod conflicts.

**Comment by colby-boucher** [comment]
I can confirm that this seems to be a conflict with Emotecraft.
[pastebin](https://pastebin.com/kdbscGda)

**Comment by 0rbid** [comment]
It also does this when you have optifine  installed which is upsetting.

**Comment by fewizz** [comment]
fixed for optifine.

**Comment by fewizz** [comment]
woks with emotecraft.
