### ISSUE TITLE
Toggleable crawl

### ISSUE THREAD

**Issue by Tachytaenius** [fewizz/Crawl#26]

**Comment by fewizz** [comment]
For 1.18, ill put it here
![image](https://user-images.githubusercontent.com/8060034/142141401-f2b94290-03bd-459b-bf31-a556326a4c2d.png)

**Comment by fewizz** [comment]
![image](https://user-images.githubusercontent.com/8060034/143658240-9e0bc358-7cac-4055-96eb-57ef5dddc814.png)
