### ISSUE TITLE
Massive console spam on version 0.10.5

### ISSUE THREAD

**Issue by SplendidAlakey** [fewizz/Crawl#32]
**MC** 1.18.2
**Fabric API** 0.50.0
**Crawl** 0.10.5

Once you join a world, the console spams the following message multiple times a second in the latest.log/server console: 
`[15:49:30] [Server thread/INFO]: [ru.fewizz.crawl.mixin.PlayerEntityMixin] false`

The issue doesn't happen on version 0.10.4

**Comment by fewizz** [comment]
oof, sorry for that.

**Comment by fewizz** [comment]
fixed in 0.10.6
