### ISSUE TITLE
MidnightControl Button Overlap

### ISSUE THREAD

**Issue by ardissaps** [fewizz/Crawl#40]
Can it be fixed overlapping button with [MidnightControl](https://modrinth.com/mod/midnightcontrols)? Thank you very much!
![image](https://user-images.githubusercontent.com/82106625/175969970-6ffaace8-6899-4acb-87a9-8cead2abd6c0.png)

I also post on their [page](https://github.com/TeamMidnightDust/MidnightControls/issues/46).

**Comment by ardissaps** [comment]
NVM I edit it with [Fancy Menu](https://www.curseforge.com/minecraft/mc-mods/fancymenu-fabric) :D
![image](https://user-images.githubusercontent.com/82106625/176354297-a276747f-87be-45e0-b071-f9b58ef41ce4.png)

**Comment by fewizz** [comment]
Good. It's still a bug tho.

**Comment by ardissaps** [comment]
Crawl is a thing that should be default, maybe set it to permanent toggle would be great, and asign hold in different key or somethig.

**Comment by ardissaps** [comment]
Fixed on [MidnightControl Side](https://github.com/TeamMidnightDust/MidnightControls/commit/735b9e87186157cb20fce3904679ff16ae4589e9).
