### ISSUE TITLE
Crawl animation glitch

### ISSUE THREAD

**Issue by qualterz** [fewizz/Crawl#42]
To reproduce hold only crawl key
Happens when the crawl key binding is in toggle mode

**Comment by fewizz** [comment]
version?

**Comment by qualterz** [comment]
Minecraft 1.19 and mod version 0.11.0

**Comment by fewizz** [comment]
thank you. ill check it out later.

**Comment by fewizz** [comment]
can't replicate.

**Comment by qualterz** [comment]
This is a demo of the glitch

https://user-images.githubusercontent.com/38355785/177991678-3a2f9758-ce6e-44bd-8403-fb1a34e11cd4.mp4

**Comment by fewizz** [comment]
any other mods?

**Comment by qualterz** [comment]
Tested with this mod and Fabric API 0.57.0 only, the problem is not in other mods

**Comment by fewizz** [comment]
Not sure what is wrong. Are you just spamming crawl key? Glithcy translation of player 1 block lower when starting swimming is vanilla behavior. Feel free to write or call me in `discord`: **fewizz#3328**

**Comment by qualterz** [comment]
Not spamming, just hold the crawl key with enabled toggle mode, that is all i did

**Comment by fewizz** [comment]
So, why are you holding key when in toggle mode? =_=

**Comment by fewizz** [comment]
Looks like it happens only on `Windows`. You can set `Sneak` to `Toggle` mode, and you will get the same behavior. So it's ok.

**Comment by qualterz** [comment]
But i ran Minecraft under Fedora Linux and this behavior does not happens with the sneak or any other vanilla movement actions

**Comment by fewizz** [comment]
Somehow related to X Window System.
