### ISSUE TITLE
[BUG] Forced server disconnect

### ISSUE THREAD

**Issue by Cm4nXD** [fewizz/Crawl#45]
With this mod installed on a server and the client of a user, if the player who has the mod installed crawls and is visible to another player whom doesn't have the mod installed, the player without the mod installed will be kicked from the server.

**Comment by fewizz** [comment]
This is expected.

**Comment by lever1209** [comment]
that shouldnt be expected considering minecraft has crawling built in

**Comment by fewizz** [comment]
The way it activates is more important. In vanilla to crawl you should put yourself in a space less than 1.5 block height. You can't crawl at any place, like with this mod. So clients with this mod installed will have slight advantage. In my opinion, having this mod installed on server and only on **some** clients is incorrect.

**Comment by fewizz** [comment]
But this behavior could be configurable...

**Comment by lever1209** [comment]
since the mod has to be installed on the server it's not unfair for other players

**Comment by Cm4nXD** [comment]
The reason I installed the mod on some clients and not others, is because I don't want people to be forced to use my modpack to play on my server. Preserving Vanilla compatibility also has the benefit of allowing geyser and floodgate to work with bedrock clients. Enabling my younger nieces and nephews whom do not own java accounts or machines capable of running my mod pack to play with us on my server.

**Comment by lever1209** [comment]
same here, im a massive fan of performance mods and optional mods that can take advantage of vanilla content to make some interesting things like spigot plugins

**Comment by iv8512** [comment]
Making it configurable would be great. I have the mod installed on my survival server where only a few people play, and having to make everyone install the mod is quite annoying, especially for people who don't have any mods installed at all or when new players join the server.

**Comment by fewizz** [comment]
> But this behavior could be configurable...

I was wrong back then, i can't implement that.

The way this mod works, it adds a new `CRAWLING` [`EntityPose`](https://maven.fabricmc.net/docs/yarn-1.21+build.1/net/minecraft/entity/EntityPose.html), thus changing [protocol](https://wiki.vg/Protocol).

There are other similar but simpler mods ([like this one](https://www.curseforge.com/minecraft/mc-mods/force-crawl)), that just put player into [`SWIMMING`](https://maven.fabricmc.net/docs/yarn-1.21+build.1/net/minecraft/entity/EntityPose.html#SWIMMING) entity pose on key press.

**Comment by lever1209** [comment]
~~could you not use the entity pose used for boats and general "entity has mounted another entity"?~~

my bad, i confused this with another mod i used recently
