### ISSUE TITLE
1.19.1 Animation is wrong for crawling.

### ISSUE THREAD

**Issue by netcore10** [fewizz/Crawl#46]
Animation is just the swimming one, for some reason.

**Comment by fewizz** [comment]
mod list?

**Comment by netcore10** [comment]
[modlist.txt](https://github.com/fewizz/crawl/files/9260104/modlist.txt)

**Comment by JLUsr** [comment]
This also happens on 1.19.2 and it appears to be caused by Lunade-FastAnim.

**Comment by fewizz** [comment]
Just looked at the `FastAnim` code. It injects it's own variant of `setAngles` method into all mob's `*Model` classes. It could indeed break compatibility.

**Comment by fewizz** [comment]
I could try to fix it on the `FastAnim` side, but it seems to be closed source. (tho i can decompile it)
Also, it seems that `FastAnim` is no longer maintained.
![image](https://github.com/user-attachments/assets/56a8d440-cc3b-49b1-bff5-ab697ce415f9)
