### ISSUE TITLE
Crawl is still using the traditional Early Riser initialisation

### ISSUE THREAD

**Issue by SleepyCatten** [fewizz/Crawl#48]
Mod Version: crawl-0.11.0
Minecraft Version: 1.19.2 with Fabric Loader 0.14.9

Log: https://gist.github.com/SleepyCatten/43288dd4651a1aecd0214845b7b41d68
Relevant message: 
"[14:38:38] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 0 override(s) found
Crawl is still using the traditional Early Riser initialisation"

**Comment by fewizz** [comment]
[Hmm, I see](https://github.com/Chocohead/Fabric-ASM/commit/9547496abb862a82b89f234fa634f81faac836cb)
