### ISSUE TITLE
Not compatible with Origins Inchling (or overall variable hitboxes)

### ISSUE THREAD

**Issue by Kryllex** [fewizz/Crawl#55]
The crawl mod has a set hitbox, when it could instead scale as a ratio/percentage of the player's detected hitbox size.

I'm not sure in what way they accomplish it, but GoProne (Fabric) for 1.19.2 does this correctly.

**Comment by footLoosely** [comment]
same here

**Comment by footLoosely** [comment]
damn

**Comment by fewizz** [comment]
fixed since 0.12.2 (#72)
