### ISSUE TITLE
Add support for Quilt Loader

### ISSUE THREAD

**Issue by anch0vie** [fewizz/Crawl#60]
![image](https://user-images.githubusercontent.com/79681820/211186027-ebd47181-243d-40c8-82f8-1e056ea8055a.png)

Hello, I am asking if this mod will support Quilt in the future? Thank you in advance!

**Comment by fewizz** [comment]
should be fixed with `0.11.5`

**Comment by anch0vie** [comment]
Thank you! Might try the mod later ;)
