### ISSUE TITLE
23w05a: Breaks MC loading options.txt

### ISSUE THREAD

**Issue by BaccarWozat** [fewizz/Crawl#63]
With 23w05a, Fabric 0.14.13, Fabric API 0.73.3, and CRAWL 0.11.5.
When the client starts it tries to load options.txt, fails (and generates an error)

`[01:00:38] [Render thread/ERROR]: Failed to load options
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_7172.method_42404()" because "$$1" is null`

As a result, player must re-enter all audio/video/resourcepack/etc. options and settings.

Workaround, of course, is to not use Crawl and wait until it updates to 1.19.4 or whatever.

**Comment by fewizz** [comment]
Can't reproduce with 1.19.4
