### ISSUE TITLE
Not compatible with Pehkui size changes

### ISSUE THREAD

**Issue by CammiePone** [fewizz/Crawl#64]
This mod works fine with the normal hitbox dimensions, but when you change the hitbox using Pehkui, the crawl hitbox remains 0.6x0.6 instead of scaling down to match the Pehkui proportions

![image](https://user-images.githubusercontent.com/16853086/221611917-8ea28417-9b22-4dda-a43e-cfcdec95b1fd.png)
![image](https://user-images.githubusercontent.com/16853086/221611973-04ba4f02-0f1d-4ebf-8404-29c5ad63dcc9.png)
![image](https://user-images.githubusercontent.com/16853086/221612050-af971f25-f5d4-47c7-8941-0a06ec33b0f3.png)
![image](https://user-images.githubusercontent.com/16853086/221612139-0974112b-6484-4b2f-9ed1-506b3a7561dd.png)

**Comment by fewizz** [comment]
Known issue

**Comment by LIXFERSI** [comment]
Wouldn't it be possible to change the current player's hitbox instead of having a fixed one?
From what I understand, this could fix Pehkui compatibility issue.
 I'm not into minecraft modding, just a question.
 
 Also, isn't the Crawl animation from the Smart Moving mod?

**Comment by fewizz** [comment]
fixed since 0.12.2 (#72)
