### ISSUE TITLE
Incompatible with VanillaIcecreamFix on Fabric 1.20.2

### ISSUE THREAD

**Issue by sternschnaube** [fewizz/Crawl#73]
Look here please: https://github.com/repletsin5/VanillaIcecreamFix/issues/24

**Comment by fewizz** [comment]
Doesn't crash since MC 1.21 (0.13.0), probably because i switched from Fabric ASM to [Mixin plugin](https://github.com/fewizz/crawl/blob/1.21.4/src/main/java/ru/fewizz/crawl/mixin/Plugin.java)
