### ISSUE TITLE
Crawling not working on multiplayer server

### ISSUE THREAD

**Issue by AzureOpus** [fewizz/Crawl#74]
While attempting to use this mod on a 1.20.1 server, the player does not start crawling and cannot fit in one block gaps. On the client side, the players view moves down into crawling position and is rubberbanded back when attempting to crawl in a one block gap.

The issue does not occur in single player with the exact same mods loaded, listed below. All mods are installed on both client and server.

[list.txt](https://github.com/fewizz/crawl/files/14293783/list.txt)

**Comment by fewizz** [comment]
Forgive me for not answering for so long.
If the problem still persists, please send me the full server log, and optionally  server/client mods.
Closing for now, feel free to reopen.
