### ISSUE TITLE
IDEA

### ISSUE THREAD

**Issue by jtx46** [fewizz/Crawl#79]
Hello! First off I like your mod. Its simple and easy to use and it has server support which is nice for our server. This posting isn't an issue but please hear me out. The mod page said Ideas could be shared on the github repository but I didn't find any links for sharing Ideas so forgive me if I'm doing this wrong. 

  My idea is all about Movement within the game. I've been searching for a mod that allows for climbing up blocks. I'm not talking about climbing fences or magically climbing 5,8,10 blocks like some recent mods. Instead I'm talking about a 'grab' button for climbing up 2 blocks without jumping and Vaulting 3 blocks high with a 'jump'>'grab'. I loved the mod Smart Moving and that's basically what I'm suggesting... https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1274224-smart-moving

Anyways thanks for reading!

**Comment by fewizz** [comment]
It is a good idea. I _might_ implement it some day, but as a separate mod (it will probably be called `Climb`)

**Comment by fewizz** [comment]
I still remember this idea, and as I said, I might implement it as a separate mod, someday, not in the near future.
