### ISSUE TITLE
compatibility with Pehkui

### ISSUE THREAD

**Issue by fewizz** [fewizz/Crawl#8]
https://www.curseforge.com/minecraft/mc-mods/pehkui

**Comment by Flyvee** [comment]
The compatibility issue I found, is that the hitbox is strange when the player's size is changed, like if they are small, their hitbox becomes bigger while crawling, higher and wider, while if the player is just increased in length, then their hitbox shrinks in height but stays the same in length/width so it is much smaller.

**Comment by fewizz** [comment]
fixed since 0.12.2 (#72)
