### ISSUE TITLE
Crawl breaks "sneak" animation

### ISSUE THREAD

**Issue by Oonicorn** [fewizz/Crawl#9]
When Crawl is installed, the sneak animation seemingly reverts to its 1.13 (taller) form for every part of the body except the legs. I noticed this because Elytra still animate according to the 1.14+ animation.

[Here's a screenshot of that animation in vanilla](https://user-images.githubusercontent.com/51089101/94725622-11f96980-032a-11eb-807d-2ef396f93d96.png)
[...and with an elytra](https://user-images.githubusercontent.com/51089101/94724782-c72b2200-0328-11eb-8836-3a504828a8b6.png)

[And here's a screenshot of that animation with Crawl and Fabric API (and only those two) installed](https://user-images.githubusercontent.com/51089101/94725832-5f75d680-032a-11eb-9a88-a5a30ee189db.png)
[and again, with an elytra for emphasis](https://user-images.githubusercontent.com/51089101/94724674-a662cc80-0328-11eb-8389-2af318a3369e.png)

**Comment by fewizz** [comment]
Thanks for report! I' ll recheck that tomorrow

**Comment by fewizz** [comment]
Please, try out [this](https://drive.google.com/file/d/1gRclcyNpxp4zVmAZ0DqwCwIPp02GFEAq/view?usp=sharing) version

**Comment by fewizz** [comment]
https://www.curseforge.com/minecraft/mc-mods/crawl/files/3071106
